---
platform: linux

params:
  REPOSITORY: concourse/dev
  DOCKERFILE: ci/dockerfiles/dev/Dockerfile
  BUILD_ARG_gdn_tag:
  IMAGE_ARG_base_image: golang-builder-image/image.tar
  IMAGE_PLATFORM: linux/amd64
  OUTPUT_OCI: false

inputs:
- name: ci
- name: dumb-init
- name: concourse
- name: gdn
- name: golang-builder-image
  optional: true
- name: containerd
  optional: true
- name: runc
  optional: true
- name: cni
  optional: true
- name: resource-types-image
  optional: true
- name: fly-linux
- name: fly-windows
- name: fly-darwin

outputs:
- name: image

caches:
- path: cache

run: {path: build}
