---
platform: linux

params:
  REPOSITORY: concourse/golang-builder
  DOCKERFILE: ci/dockerfiles/golang-builder/Dockerfile
  CONTEXT: .
  IMAGE_ARG_base_image: base-image/image.tar
  IMAGE_PLATFORM: linux/arm64,linux/amd64
  OUTPUT_OCI: true

inputs:
- name: ci
- name: golang-linux
- name: base-image

outputs:
- name: image

caches:
- path: cache

run:
  path: build
